###################### Filebeat Configuration #########################

# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  id: system-logs
  enabled: true
  paths:
    - /var/log/*.log
  # Optional filters:
  #exclude_lines: ['^DBG']
  #include_lines: ['^ERR', '^WARN']

# ============================== Filebeat modules ==============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# =============================== Kibana Setup =================================
setup.kibana:
  host: "http://<your-kibana-ip>:5601"

# ============================= Elasticsearch Output ===========================
output.elasticsearch:
  hosts: ["https://<your-es-ip>:9200"]
  username: "elastic"
  password: "<your-password>"
  protocol: "https"
  ssl.verification_mode: none

# =============================== Processors ==================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# =============================== Logging =====================================
logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 7
    rotateeverybytes: 10485760  # 10MB
